services:
  sas_kuka_control_template:
    build: https://github.com/MarinhoLab/sas_kuka_control_template.git#main:.devel/sas_kuka_control_template
    stop_signal: SIGINT
    stop_grace_period: 1m
    network_mode: "host" # Reverse connection with UR robot
    environment:
      - ROS_DOMAIN_ID
    cap_add:
      - SYS_NICE # PREEMPT_RT
    ulimits:
      rtprio: 99 # PREEMPT_RT
      rttime: -1 # PREEMPT_RT
    command: /bin/bash -c "
      cd /root/sas_tutorial_workspace/src/sas_kuka_control_template/.devel/scripts
      && chmod +x run_real_robot.sh
      && . ./run_real_robot.sh
      && ros2 launch sas_kuka_control_template real_robot_move_example_py_launch.py "
      # Always run the launch command outside of the script or it will capture the SIGINT and roslaunch will
      # not gracefully be shutdown.
